/*
 * This file is generated by jOOQ.
 */
package org.craftedsw.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import org.craftedsw.aggregate.TransactionId;
import org.craftedsw.aggregate.UserId;
import org.craftedsw.type.Currency;
import org.craftedsw.type.TransferStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoneyTransfer implements Serializable {

    private static final long serialVersionUID = -2081906859;

    private TransactionId  transactionId;
    private UserId         transferredFrom;
    private UserId         transferredTo;
    private TransferStatus status;
    private Currency       currency;
    private BigDecimal     value;
    private String         errorMessage;

    public MoneyTransfer() {}

    public MoneyTransfer(MoneyTransfer value) {
        this.transactionId = value.transactionId;
        this.transferredFrom = value.transferredFrom;
        this.transferredTo = value.transferredTo;
        this.status = value.status;
        this.currency = value.currency;
        this.value = value.value;
        this.errorMessage = value.errorMessage;
    }

    public MoneyTransfer(
        TransactionId  transactionId,
        UserId         transferredFrom,
        UserId         transferredTo,
        TransferStatus status,
        Currency       currency,
        BigDecimal     value,
        String         errorMessage
    ) {
        this.transactionId = transactionId;
        this.transferredFrom = transferredFrom;
        this.transferredTo = transferredTo;
        this.status = status;
        this.currency = currency;
        this.value = value;
        this.errorMessage = errorMessage;
    }

    public TransactionId getTransactionId() {
        return this.transactionId;
    }

    public MoneyTransfer setTransactionId(TransactionId transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    public UserId getTransferredFrom() {
        return this.transferredFrom;
    }

    public MoneyTransfer setTransferredFrom(UserId transferredFrom) {
        this.transferredFrom = transferredFrom;
        return this;
    }

    public UserId getTransferredTo() {
        return this.transferredTo;
    }

    public MoneyTransfer setTransferredTo(UserId transferredTo) {
        this.transferredTo = transferredTo;
        return this;
    }

    public TransferStatus getStatus() {
        return this.status;
    }

    public MoneyTransfer setStatus(TransferStatus status) {
        this.status = status;
        return this;
    }

    public Currency getCurrency() {
        return this.currency;
    }

    public MoneyTransfer setCurrency(Currency currency) {
        this.currency = currency;
        return this;
    }

    public BigDecimal getValue() {
        return this.value;
    }

    public MoneyTransfer setValue(BigDecimal value) {
        this.value = value;
        return this;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }

    public MoneyTransfer setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MoneyTransfer other = (MoneyTransfer) obj;
        if (transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!transactionId.equals(other.transactionId))
            return false;
        if (transferredFrom == null) {
            if (other.transferredFrom != null)
                return false;
        }
        else if (!transferredFrom.equals(other.transferredFrom))
            return false;
        if (transferredTo == null) {
            if (other.transferredTo != null)
                return false;
        }
        else if (!transferredTo.equals(other.transferredTo))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (currency == null) {
            if (other.currency != null)
                return false;
        }
        else if (!currency.equals(other.currency))
            return false;
        if (value == null) {
            if (other.value != null)
                return false;
        }
        else if (!value.equals(other.value))
            return false;
        if (errorMessage == null) {
            if (other.errorMessage != null)
                return false;
        }
        else if (!errorMessage.equals(other.errorMessage))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.transferredFrom == null) ? 0 : this.transferredFrom.hashCode());
        result = prime * result + ((this.transferredTo == null) ? 0 : this.transferredTo.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.currency == null) ? 0 : this.currency.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.errorMessage == null) ? 0 : this.errorMessage.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MoneyTransfer (");

        sb.append(transactionId);
        sb.append(", ").append(transferredFrom);
        sb.append(", ").append(transferredTo);
        sb.append(", ").append(status);
        sb.append(", ").append(currency);
        sb.append(", ").append(value);
        sb.append(", ").append(errorMessage);

        sb.append(")");
        return sb.toString();
    }
}
