/*
 * This file is generated by jOOQ.
 */
package org.craftedsw.model.tables.pojos;


import java.io.Serializable;

import org.craftedsw.aggregate.UserId;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 714776288;

    private UserId userId;
    private String email;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.email = value.email;
    }

    public User(
        UserId userId,
        String email
    ) {
        this.userId = userId;
        this.email = email;
    }

    public UserId getUserId() {
        return this.userId;
    }

    public User setUserId(UserId userId) {
        this.userId = userId;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
